# Generated by Django 5.1.6 on 2025-11-21 20:40

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(validators=[tasks.models.validate_deadline], verbose_name='Дедлайн'),
        ),
    ]
